version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

jobs:
 build:
    executor: hugo/default
    steps:
      - checkout
      - run: hugo new site .
      - run: git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
      - run: echo theme = \"ananke\" >> config.toml
      - run: |
          hugo -D -d dist
      - store_artifacts:
          path: dist