version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

jobs:
 build:
    executor: hugo/default
    steps:
      - checkout
      - run: hugo new site . --force
      - run: git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
      - run: echo theme = \"ananke\" >> config.toml
      - run: |
          hugo -D -d dist
      - store_artifacts:
          path: dist
      - run: |
          git config --global user.name "$(git show -s --format='%an' "${HEAD}")"
          git config --global user.email "$(git show -s --format='%ae' "${HEAD}")"
          git checkout -b release
          git add .
          git commit -m 'release hugo site'
          git push origin release -f 